# Generated by Django 3.1.4 on 2020-12-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='recipes.Tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='orange', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='display_name',
            field=models.CharField(default='Затрак', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
